name: glade
adopt-info: glade
summary: Create or open user interface designs for GTK+ applications
description: |

  Glade is a RAD tool to enable quick & easy development of user interfaces
  for the GTK+ 3 toolkit and the GNOME desktop environment.

  The user interfaces designed in Glade are saved as XML and these can be
  loaded by applications dynamically as needed by using GtkBuilder or used
  directly to define a new GtkWidget derived object class using
  GTK+ new template feature.

  By using GtkBuilder, Glade XML files can be used in numerous programming
  languages including C, C++, C#, Vala, Java, Perl, Python, and others.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

slots:
  # for GtkApplication registration
  glade:
    interface: dbus
    bus: session
    name: org.gnome.Glade
apps:
  glade:
    command: usr/bin/glade
    extensions: [gnome-3-28]
    plugs:
      - home
      - gsettings
      - network
    desktop: usr/share/applications/org.gnome.Glade.desktop

parts:
  glade:
    source: .
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    override-build: |
      snapcraftctl set-version $(git describe --tags | sed 's/GLADE_//g'|sed 's/_/./g')
      sed -i.bak -e 's|=org.gnome.Glade$|=${SNAP}/meta/gui/org.gnome.Glade.svg|g' data/org.gnome.Glade.desktop.in.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/apps/org.gnome.Glade.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
    organize:
      snap/glade/current/usr: usr
    build-packages:
      - gnome-common
      - libxml2-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - python-gi-dev
      - python2.7-dev
      - gtk-doc-tools
      - yelp-tools
      - intltool
      - gobject-introspection
      - libgirepository1.0-dev
